// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfmnn28fWO8dfMhgxrUQGXlKEeYWVL0BI',
    appId: '1:586920106836:web:ad7519ed29de58221806c1',
    messagingSenderId: '586920106836',
    projectId: 'college-comp',
    authDomain: 'college-comp.firebaseapp.com',
    storageBucket: 'college-comp.firebasestorage.app',
    measurementId: 'G-T01BEYWFMQ',
  );

  // TODO: Replace with your actual Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPN27pEFs6_BhSzIXtYQ9Ji7l8wHdX9lE',
    appId: '1:586920106836:android:872b8e1b152962ad1806c1',
    messagingSenderId: '586920106836',
    projectId: 'college-comp',
    storageBucket: 'college-comp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa0PvCZCyQ7jxZetuMsMC60_W-_Gp8EcQ',
    appId: '1:586920106836:ios:bf60d0acdb1848551806c1',
    messagingSenderId: '586920106836',
    projectId: 'college-comp',
    storageBucket: 'college-comp.firebasestorage.app',
    iosBundleId: 'com.collegeapp.workspace1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'college-comp',
    storageBucket: 'college-comp.appspot.com',
    iosBundleId: 'com.collegecampus.app',
  );
} 